import type { Metadata } from "next";
import { EnquiryForm } from "../components/EnquiryForm";

export const metadata: Metadata = { title: "Wholesale Laptop Supply", description: "Request bulk laptop supply for resellers, offices, schools and organisations from CHEX Computers in Lagos." };

export default function WholesalePage() {
  return <main className="inner-page"><section className="page-hero wholesale-hero section-shell"><p className="eyebrow"><span /> Bulk and corporate supply</p><h1>Laptops at scale.<br /><em>Procurement made clear.</em></h1><p>Stock-led quotations for resellers, offices, startups, schools, training centres and institutional buyers across Nigeria.</p><div className="hero-actions"><a className="button button-lime button-large" href="#quote">Request a quote</a><a className="button button-outline button-large" href="#process">See our process</a></div></section>
    <section className="wholesale-benefits section-shell">{[["01","Stock matched to your brief","Choose preferred brands, use cases and budget ranges."],["02","Testing and transparency","Exact condition and configuration confirmed before payment."],["03","Flexible mixed supply","Request business laptops, workstations or a mixed-device batch."],["04","Nationwide coordination","Delivery planning for your office, store, school or project site."]].map(([n,h,p]) => <article key={n}><span>{n}</span><h2>{h}</h2><p>{p}</p></article>)}</section>
    <section className="section section-shell wholesale-process" id="process"><div><p className="eyebrow"><span /> Procurement process</p><h2>A quote built around your actual requirement.</h2><p>We do not publish unconfirmed minimum orders or bulk discounts. Every quotation is based on current stock, quantity, configuration, condition and delivery location.</p></div><ol><li><span>01</span><b>Send your requirement</b><p>Tell us device type, quantity, location, budget and preferred brands.</p></li><li><span>02</span><b>Receive stock options</b><p>We share suitable available configurations and condition details.</p></li><li><span>03</span><b>Approve the quotation</b><p>Confirm the selected batch, delivery plan and invoice.</p></li><li><span>04</span><b>Testing and fulfilment</b><p>Units are prepared for pickup or coordinated delivery.</p></li></ol></section>
    <section className="form-section" id="quote"><div className="section-shell form-layout"><div><p className="eyebrow"><span /> Wholesale quote</p><h2>Tell us what you need.</h2><p>Complete the form and continue on WhatsApp with the prepared summary.</p></div><EnquiryForm type="wholesale" /></div></section>
  </main>;
}
